#!/bin/sh
commit_message=$(cat "$1")
if ! echo "$commit_message" | grep -qE '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test): '; then
  echo "ERROR: Commit message must start with one of the following prefixes: 'build: ', 'chore: ', 'ci: ', 'docs: ', 'feat: ', 'fix: ', 'perf: ', 'refactor: ', 'revert: ', 'style: ', 'test: '"
  exit 1
fi
